### ISSUE TITLE
Move to new organisation

### ISSUE THREAD

**Issue by betatim** [Build-a-binder/build-a-binder#17]
Any opposition to moving this repository to github.com/build-a-binder? That way the webpage can be build-a-binder.github.io

This is your last chance to suggest a less clunky name :)

**Comment by RaoOfPhysics** [comment]
I like the name. :) It is a call to action, so it calls the reader in.

**Comment by gedankenstuecke** [comment]
Agreed! :)

**Comment by betatim** [comment]
Welcome to https://github.com/Build-a-binder/build-a-binder
